# name: push Event CI

# on:
#   push:
#     branches: [ main ]

# jobs:
#   demo:
#     runs-on: ubuntu-latest

#     steps:
#       - name: printWord
#         run: echo "Hell From Kishan"

# --------------- schedule --------------

name: Schedule Job

on:
  schedule:
    - cron: "0 0 * * *" # 12:00PM

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Schedule Workflow Executed"
